---
- name: Setup Cloudflared
  include_role:
    name: papanito.cloudflared
  vars:
    cf_remove_unused_tunnel: true
    cf_cert_location: cloudflared-cert.pem
    cf_os_package_enable: true
    cf_tunnels:
      tunnel02:
        routes:
          dns:
            - "{{ vault_homeassistant_external_hostname }}"
        account_tag: '{{ vault_cloudflare_tunnel_account_tag }}'
        tunnel_secret: '{{ vault_cloudflare_tunnel_secret }}'
        tunnel_id: '{{ vault_cloudflare_tunnel_id }}'
        ingress:
          # Use cloudflare as reverse proxy for home assistant externally
          - hostname: "{{ vault_homeassistant_external_hostname }}.{{ project_tld }}"
            service: "http://{{ hostvars['home-01'].ansible_host }}:8743"
          - service: "http_status:404"
  tags: 
    - cloudflared