---
- name: Perform setup of container
  connection: ssh
  block:
    - name: Set timezone
      timezone:
        name: "{{ timezone }}"

    - name: Setup apt proxy
      block:
      - name: Setup apt proxy
        lineinfile:
          path: /etc/apt/apt.conf.d/00aptproxy
          line: Acquire::http::Proxy "http://{{ hostvars[node].ansible_host }}:3142";
          create: yes

      - name: Disable container apt cache
        lineinfile:
          path: /etc/apt/apt.conf.d/02nocache
          line: 
            Dir::Cache "";
            Dir::Cache::archives "";
          create: yes
      when: no_use_proxy is undefined or not no_use_proxy
    
    - name: Install Python
      block:
      - name: Check python is installed in container
        ansible.builtin.raw: dpkg -s python3
        register: python_install_check
        failed_when: python_install_check.rc not in [0, 1]
        changed_when: false

      - name: Install python in container
        ansible.builtin.raw: apt-get update; apt-get install -y python3
        when: python_install_check.rc == 1

    - name: Install Docker
      include_role:
        name: init-docker
      when: uses_docker is true