- name: Setup Nix
  become: true
  vars:
    ansible_python_interpreter: "/run/current-system/sw/bin/python3"
  block:
    - name: Add SOPS Age key (For runtime secrets)
      copy:
        content: "{{ vault_nix_age[inventory_hostname] }}"
        dest: "/etc/sops-age.txt"
        mode: 0500
        owner: root
        group: root

    - name: Add deploy key (for unattended SSH pulling private secrets repo)
      copy:
        content: "{{ vault_nix_deploy_key }}"
        dest: "/root/.ssh/id_ed25519"
        mode: 0500
        owner: root
        group: root

    - name: Get latest version of the flake
      become: true
      git:
        force: true
        dest: /etc/nixos/
        repo: "{{ repo }}"
      vars:
        repo: https://github.com/CertifiKate/nix-dotfiles.git

    - name: Add github to known hosts
      known_hosts:
        path: /etc/ssh/ssh_known_hosts
        name: github.com
        key: "{{ lookup('ansible.builtin.file', 'files/known_hosts-github') }}"
        
    - name: Run nixos-rebuild
      become: true
      command:
        chdir: /etc/nixos
        cmd: nixos-rebuild switch --flake .#{{ inventory_hostname }}