all:
  children:
    proxmox_servers:
      hosts:
        griddle:
          ansible_host: 192.168.10.25
          gateway: 192.168.10.1
          ethernet_interface: eno1
          project_root_directory: "/services"
          project_directory: "{{ project_root_directory }}/lxd"
          media_directory: "/mnt/storage/Media"
          storage_directory: "/mnt/storage/Storage"
          scripts_directory: "/scripts"
    physical_servers:
      hosts:
        griddle:
dev:
  hosts:
    griddle:
  children:
    pve_lxd_containers:
      hosts:
        dns-02:
        prox-01:
        auth-01:
        util-01:
        code-01:
        stor-01:
        # Requires too many hardware specific devices (second nic, zigbee adapter)
        # home-01:
        media-01:
        media-02: