all:
  children:
    proxmox_servers:
      hosts:
        microwave:
          ansible_host: 192.168.10.50
          gateway: 192.168.10.1
          ethernet_interface: enp0s31f6
          ethernet_secondary_interface: enp1s0
          project_root_directory: "/services"
          project_directory: "{{ project_root_directory }}/lxd"
          # Use direct disk rather than MergerFS endpoint just incase that has failed
          local_borg_repo_dir: "/mnt/disk1/Backups/"
          local_borg_repo_services: "{{ local_borg_repo_dir }}services-local.borg"
          # Use MergerFS storage pool
          media_directory: "/mnt/storage/Media"
          storage_directory: "/mnt/storage/Storage"
          scripts_directory: "/scripts"
          host_uses_snapraid: true
          zigbee_adapter: /dev/ttyACM0
    physical_servers:
      hosts:
        microwave:
prod:
  hosts:
    microwave:
  children:
    # ==== Physical/Cloud Servers ===========
    cloud_servers:
      hosts:
        cloud-01:
          ansible_host: "{{ cloud01_ip }}"
          ansible_user: "ansible"
          project_root_directory: "/services"
          project_directory: "{{ project_root_directory }}/apps"
          wireguard_no_frontend: true
          wireguard_port: "{{ cloud01_wireguard_port }}"
    pve_lxd_containers:
      hosts:
        dns-01:
        prox-01:
        auth-01:
        sec-01:
        gate-01:
        util-01:
        code-01:
        stor-01:
        home-01:
        media-01:
        media-02:

    # =================================

    # crowdsec_agent:
    #   hosts:
    #     sec-01:
    #       crowdsec_lapi: true
    #     auth-01: 
    #       crowdsec_agent_type: authentik
    #       crowdsec_file_mounts:
    #         - "/var/run/docker.sock:/var/run/docker.sock"
    #       crowdsec_agent_lapi_url: "http://{{ hostvars[\"sec-01\"].ansible_host }}:8080"
    #     prox-01:
    #       crowdsec_agent_type: traefik
    #       crowdsec_collections: crowdsecurity/traefik
    #       crowdsec_file_mounts:
    #         - "{{ project_directory }}/traefik/data/:/var/log/traefik/"
    #       crowdsec_agent_lapi_url: "http://{{ hostvars[\"sec-01\"].ansible_host }}:8080"
    # crowdsec_bouncer:
    #   hosts:
    #     microwave:
    #       # Iptables (all ports, incl. ssh)
    #       # May mean we don't need to do anything on prox-01 or gate-01?
    #       crowdsec_bouncer_type: iptables
    #       crowdsec_bouncer_lapi_url: "http://{{ hostvars[\"sec-01\"].ansible_host }}:8080"
    #     # prox-01:
    #     #   # Nginx/Iptables
    #     # gate-01:
    #     #   # Iptables/Wireguard
    #     # sec-01:
    #       # Cloudflared