# Used to define the configs of all PVE containers (LXC and VM)
# Dev and Prod should always have the same LXC configs, but the host and certain config options may need to be different

all:
  children:
    dev:
    prod:

    containers:
      hosts:

      # == Organised by function ======

      # ======== Core Services =========
        prox-01:
          id: 111
          node: '{{ host_server }}'
          os_type: 'nix'
          memory: 1024

        gate-01:
          id: 113
          node: '{{ host_server }}'
          os_type: 'nix'
          memory: 512
          # roles:
          #   - setup-cloudflared
          #   - setup-cloudflare-ddns

        build-01:
          id: 114
          node: '{{ host_server }}'
          os_type: 'nix'
          memory: 8192
          cores: 4

        auth-01:
          id: 115
          node: '{{ host_server }}'
          os_type: 'nix'
          memory: 1024

        avahi-01:
          id: 116
          node: '{{ host_server }}'
          os_type: 'nix'
          memory: 512
          networks:
              net0: "name=eth0,ip=dhcp,bridge=vmbr1,tag={{ vlan['server'] }}"
              net1: "name=eth0,ip=dhcp,bridge=vmbr1,tag=50"

        backup-01:
          id: 120
          node: '{{ host_server }}'
          os_type: 'nix'
          memory: 512


        # =============================
        # === Utilty (30-49) ==========
        util-01:
          id: 130
          node: '{{ host_server }}'
          os_type: 'nix'
          memory: 2048
          # roles:
          # - setup-monitoring
          # - setup-vikunja
          # - setup-recipes

        # code-01:
        #   id: 35
        #   node: '{{ host_server }}'
        #   ostemplate: '{{ debian_template }}'
        #   memory: 2048
        #   roles:
        #   - setup-coder

        # stor-01:
        #   id: 40
        #   node: '{{ host_server }}'
        #   ostemplate: '{{ debian_template }}'
        #   memory: 2048
        #   storage_directory: "/data"
        #   custom_mounts:
        #     mp1: 
        #       container_path: "/data"
        #       host_path: "{{ hostvars[ host_server ].storage_directory }}"
        #   roles:
        #   - setup-storage

        # =============================
        # === Media (50-59) ===========
        media-01:
          id: 150
          node: '{{ host_server }}'
          os_type: 'nix'
          memory: 4096
          custom_mounts:
            mp1: 
              container_path: "/data"
              host_path: "{{ hostvars[ host_server ].media_directory }}"
          # roles:
          #   - setup-jellyfin

        media-02:
          id: 151
          node: '{{ host_server }}'
          ostemplate: '{{ debian_template }}'
          memory: 4096
          custom_mounts:
            mp1: 
              container_path: "/data"
              host_path: "{{ hostvars[ host_server ].media_directory }}"
          # roles:
          #   - setup-media-dl
          #   - setup-torrent
          #   - setup-library

        # =============================
        # === Media (50-59) ===========
        mine-01:
          id: 131
          node: '{{ host_server }}'
          os_type: 'nix'
          memory: 8192
          cores: 4
          in_dmz: true