---
- name: Setup Coder
  block:
  - name: Ensure config dirs exist
    file:
      path: "{{ project_directory }}/coder/"
      state: directory
      recurse: true
      mode: 0777

  - name: Add SSH Private key
    copy:
      src: ./files/ssh-key
      dest: /coder/ssh/coder-key
      # for use in the coder container
      owner: 1000
      group: 1000
      mode: 0700

  - name: Setup Postgres Database
    include_role:
      name: generic-setup-docker-container
    vars:
      name: coder-postgres
      image: "postgres:14.2"
      ports:
        - "5432:5432"
      env:
        POSTGRES_USER: '{{ vault_coder_postgres_user }}'
        POSTGRES_PASSWORD: '{{ vault_coder_postgres_password }}'
        POSTGRES_DB: '{{ vault_coder_postgres_db }}'
      volumes:
        - '{{ project_directory}}/coder/coder-postgres/:/var/lib/postgresql/data'

  - name: Setup Coder in docker container
    include_role:
      name: generic-setup-docker-container
    vars:
      name: coder
      image: ghcr.io/coder/coder:latest
      ports:
        - "7080:7080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - "{{ project_directory }}/coder/:/home/coder/.config/"
        - "/coder/ssh/:/home/coder/.ssh/"
      env:
        CODER_PG_CONNECTION_URL: "postgresql://{{ vault_coder_postgres_user }}:{{ vault_coder_postgres_password }}@10.0.0.{{ vmid }}/{{ vault_coder_postgres_db }}?sslmode=disable"
        CODER_ADDRESS: "0.0.0.0:7080"
        CODER_ACCESS_URL: "https://code.{{ project_tld }}"
        CODER_WILDCARD_ACCESS_URL: "*.code.{{ project_tld }}"
        CODER_DERP_SERVER_STUN_ADDRESSES: "disable"
    register: coder_updated

  - name: Add proxmox lxc workspace template
    block:
      - name: Install Coder CLI (for template upload)
        command:
          cmd: curl -L https://coder.com/install.sh | sh -s --
        when: coder_updated.changed

      - name: Copy template files
        copy:
          src: "./files/"
          dest: "{{ project_directory }}/coder/templates/"
        register: copy

      - name: Template workspace file
        template:
          src: "./files/lxc-workspace/main.tf"
          dest: "{{ project_directory }}/coder/templates/lxc-workspace/main.tf"
        register: copy

      - name: Update template
        shell:
          cmd:  "coder template push -y"
          chdir: "{{ project_directory }}/coder/templates/lxc-workspace"
        no_log: true
        when: copy.changed
    