---
- name: Setup calibre-web
  block:
  - name: Ensure config dir exists
    file:
      path: "{{ project_directory }}/calibre-web/config"
      state: directory
      recurse: true
      mode: 0777
  
  - name: Setup Calibre-Web
    include_role:
      name: generic-setup-docker-container
    vars:
      name: calibre-web
      image: linuxserver/calibre-web
      ports:
        - 8083:8083
      env:
        PUID: "1000"
        PGID: "1000"
        TZ: "{{ timezone }}"
        DOCKER_MODS: "linuxserver/mods:universal-calibre"
      volumes:
        - "{{ project_directory}}/calibre-web/config/:/config"
        - "/data/Books/:/books"
