- name: Add VMs from golden image
  throttle: 1
  community.general.proxmox_kvm:
    vmid: '{{ vmid }}'
    node: '{{ node }}'
    api_user: '{{ vault_pve_api_user }}'
    api_password: '{{ vault_pve_api_password }}'
    api_host: '{{ hostvars[node].ansible_host }}'

    name: '{{ inventory_hostname }}'
    archive: "local:backup/{{ vm_templates['nix'] }}"
    timeout: 180
    cores: '{{ cores | default(1) }}'
    memory: '{{ memory | default(1024) }}'
    onboot: '{{ onboot | default(true) }}'
    sshkeys: '{{ pve_ansible_pubkey }}'
    pool: "apps"
    net:
      net0: "virtio,bridge=vmbr0,tag={{ network_tag }}"
    state: present
  register: added_vm


- name: Start VM
  community.general.proxmox_kvm:
    vmid: '{{ vmid }}'
    api_user: '{{ vault_pve_api_user }}'
    api_password: '{{ vault_pve_api_password }}'
    api_host: '{{ hostvars[node].ansible_host }}'
    state: started
  register: startVm

- name: Pause until started
  wait_for:
    host: '{{ ansible_host }}'
    port: 22
    timeout: 30
  when: startVm.changed