- name: Add VMs from golden image
  throttle: 1
  community.general.proxmox_kvm:
    vmid: '{{ vmid }}'
    node: '{{ node }}'
    api_user: '{{ vault_pve_api_user }}'
    api_password: '{{ vault_pve_api_password }}'
    api_host: '{{ hostvars[node].ansible_host }}'

    name: '{{ inventory_hostname }}'
    archive: "local:backup/{{ vm_templates['nix'] }}"
    timeout: 600
    cores: '{{ cores | default(1) }}'
    memory: '{{ memory | default(1024) }}'
    onboot: '{{ onboot | default(true) }}'
    sshkeys: '{{ pve_ansible_pubkey }}'
    pool: "apps"
    net:
      net0: "virtio,bridge=vmbr1,tag={{ network_tag }}"
    state: present
  register: added_vm


- name: Start VM
  community.general.proxmox_kvm:
    vmid: '{{ vmid }}'
    api_user: '{{ vault_pve_api_user }}'
    api_password: '{{ vault_pve_api_password }}'
    api_host: '{{ hostvars[node].ansible_host }}'
    state: started
  register: startVm

- name: Get ip of new VMs
  delegate_to: "{{ node }}"
  connection: ssh
  become: true
  shell: 
    cmd: "qm agent {{ vmid }} network-get-interfaces | grep '192.168.'"
  register: ip_command

- set_fact:
    ansible_host: "{{ ip_command.stdout_lines  | regex_search('\\d*\\.\\d*\\.\\d*\\.\\d*') }}"

- debug:
    msg: "{{ ansible_host }}"

- name: Pause until started
  wait_for:
    host: '{{ ansible_host }}'
    port: 22
    timeout: 30
  when: startVm.changed