---
- name: Restart Crowdsec Agent (LAPI)
  community.docker.docker_container:
    name: crowdsec-lapi
    container_default_behavior: compatibility
    restart: yes
  listen: restart crowdsec-lapi

- name: Restart Crowdsec Agent
  community.docker.docker_container:
    name: crowdsec-agent
    container_default_behavior: compatibility
    restart: yes
  listen: restart crowdsec-agent
