---
- name: Install required system packages
  apt: 
    pkg: 
    - 'apt-transport-https'
    - 'ca-certificates'
    - 'curl'
    - 'software-properties-common'
    - 'python3-pip'
    - 'python3-setuptools'
    - 'virtualenv'
    state: latest
    update_cache: yes
  tags:
    - dockerSetup

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add docker repository to apt
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable
    filename: docker
    state: present
    update_cache: no
  no_log: true
  tags: dockerSetup

- name: Install docker
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - fuse-overlayfs
    state: latest
    update_cache: yes
  tags: dockerSetup

- name: Ensure docker is started and enabled
  service:
    name: docker
    state: started
    enabled: yes   
  tags: dockerSetup

- name: Copy docker daemon.json file
  copy:
    src: "./templates/daemon.json"
    dest: "/etc/docker/daemon.json"
  tags: 
  - dockerSetup
  notify: restart docker-service

- name: Intall docker module for python
  pip:
    name: "docker"
  tags: dockerSetup
