---
# Gateway to handle all incoming non-local connections (i.e vpn/cloudflare tunnel)
# Only allowed to route wireguard traffic to prox-02

- name: "Setup wireguard"
  block:
  - name: "Ensure directories exist"
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ project_directory}}/wireguard-easy/config"

  - name: Secure gateway
    include_role:
      name: setup-firewalled-container
    vars:
      allowEstablished: true
      allowSSH: true
      extra_iptables_rules: |
        -N WIREGUARD
        -A FORWARD -j WIREGUARD
        -A WIREGUARD -d 10.96.80.0/24 -i wg0 -j ACCEPT
        -A WIREGUARD -d {{ hostvars["prox-01"].ansible_host }} -i wg0 -j ACCEPT
        -A WIREGUARD -i wg0 -j DROP

  - name: Create wireguard docker container
    community.docker.docker_container:
      name: wireguard
      image: weejewel/wg-easy
      pull: '{{ docker_pull }}'
      recreate: '{{ docker_recreate }}'
      hostname: wireguard
      container_default_behavior: compatibility
      capabilities:
        - NET_ADMIN
      # Run as host so we can get wg0 interface on lxd to apply iptables rules to it
      networks:
        - name: host
      restart_policy: unless-stopped
      state: started
      volumes:
        - "{{ project_directory }}/wireguard-easy:/etc/wireguard"
      env:
        # Use LXD DNS and fall back to google
        # LXD DNS maps project_tld to prox-02
        WG_DEFAULT_DNS: "10.96.80.1, 8.8.8.8"
        # Used WG only for accessing our sites
        WG_ALLOWED_IPS: "10.96.80.0/24"
        WG_HOST: "vpn.{{ project_tld }}"
        PASSWORD: "{{ vault_wg_pass }}"
  when: not wireguard_no_frontend is defined or not wireguard_no_frontend | bool
  tags: 
  - gateway
  - wireguard

- name: Install wireguard (single user)
  block:
    - name: Install Wireguard (single user)
      include_role:
        name: generic-setup-docker-container
      vars:
        name: wireguard
        image: linuxserver/wireguard
        ports:
          - "{{ wireguard_port }}:51820/udp"
        volumes:
          - "{{ project_directory }}/wireguard/config:/config"
          - "/lib/modules:/lib/modules"
        capabilities:
          - NET_ADMIN
        env:
          PEERS: "1"
          # Internal subnet
          ALLOWED_IPS: "10.0.0.0/16"
          
  when: wireguard_no_frontend is defined and  wireguard_no_frontend | bool
  tags:
  - gateway
  - wireguard