type: leaky
name: CertifiKate/authentik_user_enum
description: "Detect authentik brute force"
filter: evt.Meta.log_type == 'authentik_failed_auth'
distinct: evt.Meta.target_user
groupby: evt.Meta.source_ip
leakspeed: 1m
capacity: 5
blackhole: 1m
labels:
  service: authentik
  type: bruteforce
  remediation: true