type: leaky
name: CertifiKate/authentik_bf
description: "Detect Authentik brute force"
filter: evt.Meta.log_type == 'authentik_failed_auth'
groupby: evt.Meta.source_ip
leakspeed: 1m
capacity: 5
labels:
  service: authentik
  type: bruteforce
  remediation: true