# Defines a wrapper to install a docker container with reasonable fallbacks and defaults
# - Lets us do checks for networks and such

- block:
  - name: Ensure networks exist
    community.docker.docker_network:
      name: "{{ item.name }}"
    loop: "{{ networks }}"
    when: networks is defined
    
  - name: "Install Container - {{ name }}"
    community.docker.docker_container:
      name: '{{ name | mandatory}}'
      image: '{{ image | mandatory}}'
      pull: '{{ docker_pull }}'
      recreate: '{{ docker_recreate }}'
      hostname: '{{ name | mandatory }}'
      container_default_behavior: compatibility
      restart_policy: unless-stopped
      network_mode: default
      capabilities:
        '{{ capabilities | default([]) }}'
      networks: 
        '{{ networks | default([]) }}'
      ports:
        '{{ ports | default([]) }}'
      volumes:
        '{{ volumes | default([]) }}'
      command: '{{ command | default() }}'
      env:
        '{{ env | default({}) }}'
      devices:
        '{{ devices | default([]) }}'
  tags: always