- name: Create Nix Golden LXC template
  hosts: build-01
  become: true
  gather_facts: false
  vars:
    build_server: build-01
    input_repo: "https://github.com/CertifiKate/nix-dotfiles"
    input_config_path: "golden.nix"
    output_name: "nixos-24.05-golden.tar.xz"
    output_path: "/var/lib/vz/template/cache/{{ output_name }}"
    output_host: "microwave"
  tasks:

  - name: Create image
    block:
      - name: Clone repo
        git:
          repo: "{{ input_repo }}"
          dest: /tmp/nixos
        register: copyConfig

      - name: Run Generator
        command:
          chdir: /tmp/nixos
          cmd: |
            nix run github:nix-community/nixos-generators -- 
            --format proxmox-lxc
            --disk-size 4096
            --configuration /tmp/nixos/{{input_config_path}}
        register: runGenerator

      - name: Print filename
        debug:
          msg: "File Name: {{ runGenerator.stdout }}"

  - name: Get generated image onto proxmox
    block:
    - name: Pull image from build server onto local device
      become: false
      fetch:
        src: "{{ runGenerator.stdout }}"
        dest: "/tmp/{{ output_name }}"
        flat: true


    - name: Copy image to proxmox node
      delegate_to: "{{ output_host }}"
      copy:
        src: "/tmp/{{ output_name }}"
        dest: "{{ output_path }}"

