# Reset the development environment by removing all LXC containers and configs, then restoring latest backup

- name: Teardown LXC containers
  hosts: dev:&pve_lxd_containers
  connection: local
  gather_facts: false
  tasks:
  - name: 
    block:
    - name: Stop containers
      community.general.proxmox:
        vmid: '{{ vmid }}'
        api_user: '{{ pve_api_user }}'
        api_password: '{{ pve_api_password }}'
        api_host: '{{ hostvars[node].ansible_host }}'
        state: stopped
        force: true
      ignore_errors: true

    - name: Remove containers
      community.general.proxmox:
        vmid: '{{ vmid }}'
        api_user: '{{ pve_api_user }}'
        api_password: '{{ pve_api_password }}'
        api_host: '{{ hostvars[node].ansible_host }}'
        state: absent
        purge: true
        force: true
      ignore_errors: true
  tags:
    - never
    - teardown

- name: Restore configs from prod backup
  hosts: dev:&proxmox_servers
  gather_facts: false
  become: true
  tasks:
    - name: Clear old files
      file:
        path: "{{ project_directory }}"
        state: absent

    - name: Create folder
      file:
        owner: root
        mode: 0777
        path: "{{ project_directory }}"
        state: directory

    - name: Copy ssh key
      copy:
        src: ../inventory/group_vars/dev/borg-read-only.key
        dest: /tmp/borg-key
      no_log: true

    - name: Get latest backup
      become: false
      shell:
        cmd: "BORG_PASSPHRASE={{ vault_borgbackup_key_local_services }} borg list svc_backup@192.168.10.50:/mnt/disk1/Backups/services-local.borg --last 1 --short --rsh 'ssh -i /tmp/borg-key'"
      register: latest_backup
      no_log: true

    - name: Get latest backup size
      become: false
      shell:
        cmd: "BORG_PASSPHRASE={{ vault_borgbackup_key_local_services }} borg info svc_backup@192.168.10.50:/mnt/disk1/Backups/services-local.borg --json --rsh 'ssh -i /tmp/borg-key'"
      register: latest_backup_size
      no_log: true

    - set_fact:
        latest_backup_size_bytes: "{{ (latest_backup_size.stdout | from_json).cache.stats.total_size }}"
      no_log: true

    - name: Restore from backup
      become: false
      shell:
        cmd: "BORG_PASSPHRASE={{ vault_borgbackup_key_local_services }} borg extract svc_backup@192.168.10.50:/mnt/disk1/Backups/services-local.borg::{{ latest_backup.stdout }} --rsh 'ssh -i /tmp/borg-key'"
        chdir: /home/ansible/
      # async: 1000
      # poll: 0
      register: backup_progress
      no_log: true
    
    # - name: Backup progress
    #   shell:
    #     cmd: du /home/ansible/services -d0 | cut -f1
    #   failed_when: false
    #   # poll: 10000
    #   # retries: 0
    #   # loop: "{{ backup_progress.results }}"
    #   # loop_control: 
    #   #   loop_var: "async_result_item"
    #   register: backup_progress_async
    #   until: backup_progress_async.finished

    
    - name: Move backup to correct spot
      become: true
      shell:
        cmd: "mv /home/ansible/services/* /services"

  tags: restore-config

- name: Re-provision proxmox
  import_playbook: provision_proxmox.yml
