- name: Setup services
  hosts: pve_lxd_containers
  gather_facts: false
  order: sorted
  tasks:
    - name: Run roles
      include_role:
        name: '{{ role_item }}'
      when: roles is defined
      loop: '{{ roles }}'
      loop_control:
        loop_var: role_item

- name: Setup Crowdsec Agents
  hosts: crowdsec_agent
  gather_facts: false
  roles:
    - "setup-crowdsec-agent"
  
- name: Setup Crowdsec Bouncers
  hosts: crowdsec_bouncer
  become: true
  gather_facts: false
  roles:
    - "setup-crowdsec-bouncer"
