---
- name: "Setup minecraft server"
  hosts: "cloud-01"
  become: yes
  gather_facts: true
  pre_tasks:
  - name: "Setup system"
    block:
    - name: "Update cache & update system"
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: true

    - name: Check python is installed in container
      ansible.builtin.raw: dpkg -s python3
      register: python_install_check
      failed_when: python_install_check.rc not in [0, 1]
      changed_when: false

    - name: Install python in container
      ansible.builtin.raw: apt-get update; apt-get install -y python3
      when: python_install_check.rc == 1

      # Docker Setup
    - name: Setup docker
      include_role:
        name: init-docker
    tags: 
      - never
      - setup

  - name: Setup Mincraft server
    include_role:
      name: setup-minecraft

  roles:
    - "setup-minecraft"
    - "setup-gateway"