---
- name: Install Authentik Postgres
  include_role:
    name: generic-setup-docker-container
  vars:
    name: authentik-postgresql
    image: postgres:12-alpine
    networks: 
      - name: authentik
    volumes:
      - "{{ project_directory }}/authentik/postgres/data:/var/lib/postgresql/data"
    env:
      POSTGRES_PASSWORD: "{{ vault_authentik_postgres_pass }}"
      POSTGRES_USER: "{{ vault_authentik_postgres_user }}"
      POSTGRES_DB: "{{ vault_authentik_postgres_name }}"
  tags:
    - authentik

- name: Install Authentik Redis
  include_role:
    name: generic-setup-docker-container
  vars:
    name: authentik-redis
    image: redis:alpine
    networks: 
      - name: authentik
  tags:
    - authentik

- name: Install Authentik Server
  include_role:
    name: generic-setup-docker-container
  vars:
    name: authentik-server
    image: ghcr.io/goauthentik/server
    command: server
    networks: 
      - name: authentik
    ports:
      - '9443:9443'
    env:
      AUTHENTIK_REDIS__HOST: "authentik-redis"
      AUTHENTIK_POSTGRESQL__HOST: "authentik-postgresql"
      AUTHENTIK_POSTGRESQL__USER: "{{ vault_authentik_postgres_user }}"
      AUTHENTIK_POSTGRESQL__NAME: "{{ vault_authentik_postgres_name }}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "{{ vault_authentik_postgres_pass }}"
      AUTHENTIK_SECRET_KEY: "{{ vault_authentik_secret }}"
    volumes:
      - "{{ project_directory }}/authentik/server/media:/media"
      - "{{ project_directory }}/authentik/server/custom-templates:/templates"
  tags:
    - authentik

- name: Install Authentik Worker
  include_role:
    name: generic-setup-docker-container
  vars:
    name: authentik-worker
    image: ghcr.io/goauthentik/server
    command: worker
    networks: 
      - name: authentik
    env:
      AUTHENTIK_REDIS__HOST: "authentik-redis"
      AUTHENTIK_POSTGRESQL__HOST: "authentik-postgresql"
      AUTHENTIK_POSTGRESQL__USER: "{{ vault_authentik_postgres_user }}"
      AUTHENTIK_POSTGRESQL__NAME: "{{ vault_authentik_postgres_name }}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "{{ vault_authentik_postgres_pass }}"
      AUTHENTIK_SECRET_KEY: "{{ vault_authentik_secret }}"
  tags:
    - authentik

- name: Install Authentik LDAP Outpost
  include_role:
    name: generic-setup-docker-container
  vars:
    name: authentik-ldap
    image: ghcr.io/goauthentik/ldap
    networks: 
      - name: authentik
    ports:
      - "3389:3389"
    env:
      AUTHENTIK_HOST: "https://authentik-server:9443"
      AUTHENTIK_INSECURE: "true"
      AUTHENTIK_TOKEN: "{{ vault_authentik_ldap_token}}"
  tags:
    - authentik