---
- name: Setup Traefik
  block:
  - name: Ensure Traefik Directory Exist
    file:
      path: "{{ project_directory }}/traefik/{{ item }}"
      state: directory
    with_items:
      - config/providers
      - data

  - name: Ensure Traefik Configuration Files Exist
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - {src: ./traefik.yml.j2, dest: "{{ project_directory }}/traefik/config/traefik.yml"}
    notify: restart traefik
    
  - name: Ensure Traefik dynamic files exist
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "0700"
    with_items:
      - {src: ./providers.yml.j2, dest: "{{ project_directory }}/traefik/config/providers/services.yml"}

  - name: Create Traefik Docker Container
    include_role:
      name: generic-setup-docker-container
    vars:
      name: traefik
      image: traefik
      networks: 
        - name: proxy
      ports:
          - "80:80"
          - "443:443"
          - "9104:9104"
          - "8080:8080"
      env:
        CLOUDFLARE_EMAIL: "{{ vault_cloudflare_email }}"
        CLOUDFLARE_DNS_API_TOKEN: "{{ vault_cloudflare_api_token }}"
      volumes:
        - "{{ project_directory }}/traefik/config/:/etc/traefik/"
        - "{{ project_directory }}/traefik/data/:/etc/traefik/data/"

- name: Setup HTTP Error Page Server
  include_role:
    name: generic-setup-docker-container
  vars:
    name: http-error-pages
    image: tarampampam/error-pages
    networks: 
      - name: proxy
    env:
      TEMPLATE_NAME: "connection"
  tags:
    - error-pages