---

- name: Setup Vikunja
  block:
  - name: Setup directories
    file:
      path: "{{ project_directory }}/vikunja/{{item}}/"
      state: directory
    with_items:
      - db
      - api/files

  - name: Setup Vikunja Database
    include_role:
      name: generic-setup-docker-container
    vars:
      name: vikunja-db
      image: "mariadb:10"
      ports:
        - 3306:3306
      volumes:
        - "{{ project_directory }}/vikunja/db/:/var/lib/mysql"
      networks:
        - name: vikunja
      env:
        MYSQL_ROOT_PASSWORD: "{{ vault_vikunja_db_root_pw }}"
        MYSQL_USER: vikunja
        MYSQL_PASSWORD: "{{ vault_vikunja_db_vikunja_pw }}"
        MYSQL_DATABASE: vikunja
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  - name: Setup Vikunja API
    include_role:
      name: generic-setup-docker-container
    vars:
      name: vikunja-api
      image: "vikunja/api"
      ports:
        - 3456:3456
      volumes:
        - "{{ project_directory }}/vikunja/api/files/:/app/vikunja/files"
      networks:
        - name: vikunja
      env:
        VIKUNJA_DATABASE_HOST: vikunja-db
        VIKUNJA_DATABASE_PASSWORD: "{{ vault_vikunja_db_vikunja_pw }}"
        VIKUNJA_DATABASE_TYPE: mysql
        VIKUNJA_DATABASE_USER: vikunja
        VIKUNJA_DATABASE_DATABASE: vikunja
        VIKUNJA_SERVICE_JWTSECRET: "{{ vault_vikunja_jwtsecret }}"
        VIKUNJA_SERVICE_FRONTENDURL: https://vikunja.{{ project_tld }}/
        VIKUNJA_SERVICE_ENABLEREGISTRATION: 'true'
        
  - name: Setup Vikunja Frontend
    include_role:
      name: generic-setup-docker-container
    vars:
      name: vikunja
      image: "vikunja/frontend"
      ports:
        - 3457:80
      env:
        VIKUNJA_API_URL: https://vikunja.{{ project_tld }}/api/v1
