---
# Ensure repository is setup

- name: Add crowdsec repo
  script: 
    creates: /etc/apt/sources.list.d/crowdsec_crowdsec.list
    command: "curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh > /tmp/crowdsec-setup.sh; chmod +x /tmp/crowdsec-setup.sh; /tmp/crowdsec-setup.sh; rm /tmp/crowdsec-setup.sh"
  tags: 
  - crowdsec-bouncer

- name: Install and configure Firewall Bouncer
  block:
  - name: Install Firewall Bouncer
    apt: 
      pkg: crowdsec-firewall-bouncer-iptables
      state: latest
      update_cache: yes

  - name: Copy firewall bouncer config
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    with_items:
      - {src: firewall-bouncer-config.yaml.j2, dest: "/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml"}
  
  - name: Check if bouncer is registered
    delegate_to: sec-01
    command:
      cmd: docker exec crowdsec-lapi cscli bouncers list -o raw
    register: registration_response
    changed_when: false

  - name: Add bouncer to LAPI
    delegate_to: sec-01
    command:
      cmd: "docker exec crowdsec-lapi cscli bouncers add {{ inventory_hostname }}-firewall -k {{ vault_crowdsec_bouncer_key[inventory_hostname] }}"
    changed_when: false
    when: inventory_hostname not in registration_response.stdout

  - name: "Enable bouncer service"
    service:
      name: crowdsec-firewall-bouncer
      state: started
      enabled: yes
  tags:
    - crowdsec-bouncer
    - crowdsec-bouncer-firewall